CREATE TABLE TASK_ADMIN(
ADMIN_ID INT PRIMARY KEY IDENTITY(1,1),
ADMIN_NAME VARCHAR(500)
);



CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT PRIMARY KEY IDENTITY(1,1),
TASK_MASTER INT,
EMPLOYEE_NAME VARCHAR(500),
EMPLOYEE_EMAIL VARCHAR(500),
FOREIGN KEY (TASK_MASTER) REFERENCES TASK_ADMIN(ADMIN_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);



CREATE TABLE TASK(
TASK_ID INT PRIMARY KEY IDENTITY(1,1),
EMPLOYEE_ID INT,
TASK_NAME VARCHAR(500),
TASK_DESC VARCHAR(2000),
IS_COMPLETE INT DEFAULT 0,
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);



INSERT INTO TASK_ADMIN VALUES ('FAISAL'),('ADNAAN');

INSERT INTO EMPLOYEES VALUES (1,'vj','VJ@GM.COM'),(1,'MAZ','MAZ@GM.COM'),(2,'PRIT','PRIT@GM.COM');

INSERT INTO TASK(EMPLOYEE_ID,TASK_NAME,TASK_DESC) VALUES (2,'SEARCH FILES', 'OPEN EXPLORER AND SEARCH')
INSERT INTO TASK(EMPLOYEE_ID,TASK_NAME,TASK_DESC) VALUES (1,'CHECK FILES', 'OPEN FILES AND CHECK')
INSERT INTO TASK(EMPLOYEE_ID,TASK_NAME,TASK_DESC) VALUES (3,'RENAME FILES', 'SELECT FILES AND RENAME')
INSERT INTO TASK(EMPLOYEE_ID,TASK_NAME,TASK_DESC) VALUES (2,'DELETE FILES', 'SELECT FILES AND DELETE')

UPDATE TASK SET IS_COMPLETE = 1 WHERE EMPLOYEE_ID = 2

--DELETE FROM TASK_ADMIN WHERE ADMIN_ID = 2;

SELECT * FROM TASK_ADMIN;
SELECT * FROM EMPLOYEES;
SELECT * FROM TASK;

--DROP TABLE TASK;
--DROP TABLE EMPLOYEES;
--DROP TABLE TASK_ADMIN;